---

  ## Make sure you have these labels - the description doesn't matter - and use one of them in your PR to create new release:
  # gh label create major --description "semver: backwards incompatible changes"
  # gh label create minor --description "semver: backwards compatible new functionalities"
  # gh label create patch --description "semver: backwards compatible bug fixes"
  
  name: Semantic Versioning
  
  on:
    pull_request:
      branches: [master, main]
      types: [closed]
  
  jobs:
    semver-release:
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged
      steps:
        - name: Create semver tag
          uses: K-Phoen/semver-release-action@master
          id: release
          with:
            release_branch: ${{ github.event.pull_request.base.ref }}
            release_strategy: release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
        - name: Create release comment
          if: steps.release.outputs.tag != ''
          uses: peter-evans/create-or-update-comment@v2
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: "Created semver release: ${{ steps.release.outputs.tag }}"
  
        - name: Create skipping comment
          if: steps.release.outputs.tag == ''
          uses: peter-evans/create-or-update-comment@v2
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: "No semver release labels, skipping the release."
  
