name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-action/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          version-file: version.txt